### ISSUE TITLE
2.6.1版本加了此MOD会导致游戏卡在加载页面33%处

### ISSUE THREAD

**Issue by xiaolfc** [Keriils/NH-Utilities#45]
2.6.1版本加了此MOD会导致游戏卡在加载页面33%处

**Comment by Keriils** [comment]
@xiaolfc  目前没适配261的 相关适配版本之后发布

**Comment by xiaolfc** [comment]
是我把生活调味料mod删除才会导致卡进度的，nhutilities这个mod能在2.6.1使用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月17日(周日) 下午4:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Keriils/NH-Utilities] 2.6.1版本加了此MOD会导致游戏卡在加载页面33%处 (Issue #45)




 
@xiaolfc  目前没适配261的 相关适配版本之后发布

**Comment by Keriils** [comment]
你可以尝试去config关闭enableLunchBoxPlus
