### ISSUE TITLE
超级治愈之斧兼容

### ISSUE THREAD

**Issue by mcmso** [Keriils/NH-Utilities#60]
https://paste.ubuntu.com/p/H9gwH2fD63/       手持超级治愈之斧一直后台无限刷新日志瞬间卡死

**Comment by Keriils** [comment]
详细说明下情况

**Comment by mcmso** [comment]
> 详细说明下情况

手持治愈之斧崩溃

**Comment by Keriils** [comment]
额 版本信息什么的 我得复现问题

**Comment by mcmso** [comment]
https://modrinth.com/mod/asjcore/version/1.4.2.2 这个和最新版的nhu

**Comment by Keriils** [comment]
我这边测试加你说的mod 版本是1.4.2.2 进去就崩溃 
我什么都没做 反正就是我目前我无法复现这个问题 你那边的崩溃只能看出部分问题

**Comment by Keriils** [comment]
我不清楚这个mod 你们那边是怎么加进去的（

**Comment by mcmso** [comment]
> 我不清楚这个mod 你们那边是怎么加进去的（

私货

**Comment by mcmso** [comment]
> 我这边测试加你说的mod 版本是1.4.2.2 进去就崩溃 我什么都没做 反正就是我目前我无法复现这个问题 你那边的崩溃只能看出部分问题

崩溃是因为biome
id冲突

**Comment by mcmso** [comment]
你给他配置文件的46改成254就行了

**Comment by Keriils** [comment]
行 我看看

**Comment by Keriils** [comment]
修复 #62
