### ISSUE TITLE
神秘获取研究笔记问题

### ISSUE THREAD

**Issue by LunerArrow** [Keriils/NH-Utilities#61]
魔导手册获取研究笔记会直接踢出服务器
![c4690fa5-d010-43af-8298-9b145628a6ba](https://github.com/user-attachments/assets/e33cc824-12e3-476d-9e87-a2ba613054d2)

**Comment by Keriils** [comment]
目前还没找到问题所在 无法复现

**Comment by Keriils** [comment]
如果有具体的log 或者 crash report  指的是服务器那边的 请发出来

**Comment by Keriils** [comment]
@Tctraveler

**Comment by Tctraveler** [comment]
我这边在单机和服务器都无法复现你的问题

**Comment by LunerArrow** [comment]
[Uploading fml-server-latest.log…]()

**Comment by LunerArrow** [comment]
[fml-server-latest.log](https://github.com/user-attachments/files/18266292/fml-server-latest.log)

**Comment by Keriils** [comment]
[21:21:16] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: Cannot read field "parents" because the return value of "thaumcraft.api.research.ResearchCategories.getResearch(String)" is null
	at Launch//thaumcraft.common.lib.research.ResearchManager.doesPlayerHaveRequisites(ResearchManager.java:517) ~[ResearchManager.class:?]

你是不是在 21点21分左右蹦出服务器的 @LunerArrow

**Comment by Keriils** [comment]
我看到了 [21:21:16] [Server thread/INFO] [qz_miner/]: 玩家: promisesky 已登出，连锁实例中已删除
[21:21:16] [Server thread/DEBUG] [NotEnoughItems/]: Unloading Player: promisesky

**Comment by LunerArrow** [comment]
是的

**Comment by Keriils** [comment]
@LunerArrow  我们仔细看了下 这个问题可能是神秘本体那边的未知问题  我们也不好复现这个 你指令解锁下好吧
真不好解决（

**Comment by Keriils** [comment]
@LunerArrow  等下 好像有铸币TC那边写错了（我让他看看

**Comment by Keriils** [comment]
![image](https://github.com/user-attachments/assets/86a87db0-05ad-49db-bdaa-5a82f3117848)

**Comment by Keriils** [comment]
不好说什么了.....  问题解决（  服务端没加nhu。。。
